### PR TITLE
Add Forward / Back as Three Finger Gesture -> Wip/show desktop algorithms

### LINKED ISSUE #23: Request: Three Finger Gestures for Forward/Back
I would love to have an option for three figure gestures left/right to be forward/back in browsers and other windows. I personally have it follow natural scrolling (swiping right goes back, swiping left goes forward), but I imagine others would like to have a toggle to switch between natural scrolling too.

An option to select gestures for three finger gestures (selecting window switching, or forward/back) would be great! Selecting gestures for 4 finger gestures too may be nice if other users would like that too.

### PR DESCRIPTION
**Pull request by AchimStuy**
* Add Forward / Back as Three Finger Horizontal Swipe
* In settings user can customize, whether he wants Alt+Tab or Forward / Back

Fixes #23
Like #39, but resolves conflicts with `Wip/show desktop algorithms`

### CODE REVIEW

**Comment by harshadgavali** [comment]
Thank you @AchimStuy !!

**Comment by AchimStuy** [comment]
Thank you @harshadgavali for merging! :)

**Comment by harshadgavali** [comment]
@AchimStuy 
I have added arrow animation.
I'll think on how to present preference (current preference breaks old configuration)
Then I'll merge this to main.

**Comment by AchimStuy** [comment]
@harshadgavali Nice!
What exactly do you mean? The preference UI or Gnome's preference storage system? I expected that.. I just reconfigured my settings, though that's not really user friendly. If you point me in a direction, I might also have a look..
Looking forward to have my modifications in official extension.

**Comment by harshadgavali** [comment]
I meant preference storage system and UI too, If someone has disabled tab switching gesture, updating will enable it.

For UI,
It's not actually 3 finger horiz gesture, It can be 4 finger gesture too by turning 4-finger workspace switching gesture off.
(I know, not the best names :|).
So all remaining 3/4 finger horiz/vert gestures should be combo boxes as well.

I thing doing one time migration from old preference to new one might solve the issue or doing one time breaking update with GS42.
I'm leaning towards breaking update with GS42, which will break many extensions anyway.

**Comment by matthijskooijman** [comment]
What's the plan with this PR? I saw it was merged, so I pulled the git main version, to be surprised that it wasn't included. Seems this was merged into the wip/show-desktop-algorithms branch for some reason? The main subject commit of that branch seem to have been merged to main, but not this one?

Anyway, I cherry-picked the merge commit onto main, which seems to fine for me now. There was one conflict in prefs.ui (I suspect due to an indentation change), here's the commit with the conflict fixed, if that's helpful: https://github.com/matthijskooijman/gnome-gesture-improvements/commit/f00a2bc9e744a01397a63d5e477d27ad40585a2b

**Comment by harshadgavali** [comment]
@matthijskooijman 
I wanted to migrate preference from gtk4 to libadwaita before merging this to main branch, but i need typescript bindings for this, otherwise i'd have to redesign prefs twice.

Issue to publish bindings to npmjs is here https://github.com/gi-ts/gtk4/issues/1.
either that resolves or i have to learn to generate bindings myself.

unfortunately I didn't have much time, so [milstone#2](https://github.com/harshadgavali/gnome-gesture-improvements/milestone/2) will get pushed further back.

**Pull request merged**
